apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogeraldoluizapi
  namespace: development
  labels:
    app: ogeraldoluizapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ogeraldoluizapi
  template:
    metadata:
      labels:
        app: ogeraldoluizapi
    spec:
      containers:
        - name: ogeraldoluizapi
          image: geraldobl58/ogeraldoluizapi:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi