apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: development
spec:
  type: ClusterIP  # Pode ser ClusterIP, jรก que o Ingress vai expor
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000